tinymce/views.py

Django have removed simplejson from upcoming versions.
https://docs.djangoproject.com/en/dev/releases/1.7/#features-removed-in-1-7

simplejson is no more remain in django.

---

docs/usage.rst

Added some examples of using TinyMCE `setup` method as well as adding custom plugins. English is not my native language so you are welcome to correct it.

Extended documentation

---

.gitignore
.travis.yml
Makefile
tinymce/tests/test_views.py
tox.ini

Configure tox to be able to run tests locally.

---

tinymce/compressor.py
tinymce/tests/test_compressor.py
tinymce/tests/test_views.py

As promised, add test for compressor.
If there is some way to improve it, I'll be pleased to hear.

Test compressor

---

tinymce/urls.py
tinymce/views.py

There were two old views with templates that doesn't exist anymore.
I've deleted them.

[Cleanup] delete old views

---

README.rst

I have changed all badges to shields.io service

[Feat] move images to shields.io

---

docs/installation.rst

As title, this PR updated the links in installation instruction.

Updated links in the installation instruction

---

README.rst

Add information about current Release and support.

[Doc] update docs to clear out version supporting

---

.travis.yml

Add PyEnchant dependencies to travis.

---

CONTRIBUTORS.rst
tinymce/views.py
tinymce/widgets.py

Most try/except clauses were for Django < 1.6.

Cleaned imports

---

tinymce/static/django_tinymce/init_tinymce.js
tinymce/widgets.py

This pull request addresses issues #152 and #166 and is an alternative to pull requests #151 and #189. Since some people might want to use anonymous functions, I am using `eval` in JavaScript. I'm not thrilled about this, but that's what worked (see [this Stack Overflow question](http://stackoverflow.com/q/2573548/237244) for more information).

Add support for JavaScript functions

---

CHANGELOG.rst
tinymce/tests/test_widgets.py
tinymce/widgets.py

Fixed client-side browser validation with required form fields

---

CHANGELOG.rst
tinymce/tests/test_widgets.py
tinymce/widgets.py

Prevented crash when no language are activated

---

README.rst

@Natim I'm not sure if this is what you have in mind.

Update badges for Travis CI and Coveralls. Fix #227

---

tinymce/models.py
tinymce/settings.py

Fallback on os.path if the INSTALLED_APPS is not properly loaded.

---

tinymce/static/django_tinymce/init_tinymce.js

Fix initialization crash when clicking on an SVG element

---

docs/installation.rst
tinymce/tests/test_widgets.py
tinymce/widgets.py

Thanks @andre-silva-14 for the initial patch.

Give priority to config language over Django language

---

docs/usage.rst

The preview code was removed in f75c6bca86925bfdce417119b11d36219736a6a0.

Removed leftover preview button documentation

---

tinymce/tests/test_widgets.py
tinymce/widgets.py

Fixes #285 - Match language code with existing translation files

---

setup.cfg

Python 2 is no longer supported.

No more needs for universal builds

---

tox.ini

Not needed since 79d64806f22b0ba1003c87cd2fdd143e9875b854

Removed mock from tox environments

---

docs/installation.rst

Thanks Márton Molnár for the report.

Fixes #345 - Fixed default TINYMCE_DEFAULT_CONFIG in docs

---

docs/installation.rst

Added some indentation to a code block as it was not being formatted correctly on the documentation page!

Added indentation to codeblock to format correctly

---

README.rst

resolve https://github.com/jazzband/django-tinymce/issues/411

update readme link

---

tinymce/settings.py

To fix issue https://github.com/jazzband/django-tinymce/issues/420

Switch to using proper staticfiles_storage.url() call to reference the TinyMCE JS
