- docs/installation.rst
> Change MEDIA_ROOT to MEDIA_URL for TINYMCE_JS_URL

- tinymce/compressor.py
I ran into and issue with my AWS / S3 deployment where it was not finding the files until I applied this fix
> Enable the use of staticfiles finder in compressor when it is installed

- tinymce/static/django_tinymce/init_tinymce.js
Safely handle cases where jQuery comes form admin (and is called django.jQuery) and where it is loaded outside of admin (and is called jQuery).
> Handle non-admin jQuery

- tinymce/settings.py
Here I've added some quick and dirty fix when using STATICFILES_DIRS instead of STATIC_ROOT.
> Fix for crashes when using tinymce in STATICFILES_DIRS in development mode.

- tinymce/static/django_tinymce/init_tinymce.js
Fixes #124. Changed the order of the parameter passing and added checks against "undefined" for django and django.jQuery to preserve the preference for django.jQuery if it is defined.
> Fixed django.jQuery vs. jQuery passing issue in init_tinymce.js

- tinymce/urls.py
Conflicts:
tinymce/urls.py
Fixes #145
> Fixed Django 1.9 compatibility: Pass views as callables, not as strings

- tinymce/urls.py
- tinymce/views.py
- tinymce/widgets.py
`django.utils.datastructures.SortedDict` was deprecated in Django 1.7 and finally removed in 1.9.
The semantics are the same as the stdlib's `collections.OrderedDict`, so fall back to that.
> [tinymce4] Django 1.9 compatibility

- docs/installation.rst
I tried walking through the Testing instructions and they didn't seem quite complete or correct. I have just verified these instructions using the latest version of Django.
Note that even when these instructions are followed completely, the app still doesn't work until you disable the spellchecker plugin. I debugged and found that there is an assumption that plugins will have a "langs" directory, and that is missing for the spellchecker plugin, so tinymce is unable to load.
> Updated Testing instructions

- CONTRIBUTORS.rst
- tinymce/static/tiny_mce/plugins/media/js/media.js
Embedding videos doesn't work for websites that use https in modern browsers due to mixed-content policy (codes are generated with http).
I've removed hardcoded protocol string from code that is generated for embeds.
> Remove hardcoded protocol from embeds

- tinymce/views.py
Chrome browser rejects the file 'http://domain/tinymce/filebrowser/'. This message get in the console browser:
```
Refused to execute script from 'http://domain/tinymce/filebrowser/'
because its MIME type ('text/html') is not executable, and strict MIME
type checking is enabled.
```
The patch fixes this of course.
> FIX: Refused to execute script

- tinymce/widgets.py
Fixed a JSON parsing error because of the missing quoting if paste_preprocess or paste_postprocess was set in TINYMCE_DEFAULT_CONFIG
https://github.com/aljosa/django-tinymce/issues/166
> Fixed paste_preprocess & paste_postprocess if set in TINYMCE_DEFAULT_CONFIG

- docs/installation.rst
- tinymce/settings.py
- tinymce/widgets.py
This is possibly enough to close #28. Although it doesn't touch the `TINYMCE_FILEBROWSER` setting, it does allow for other file browsers. For example:
```python
TINYMCE_DEFAULT_CONFIG = {
...
'file_browser_callback': "CustomFileBrowser",
}
TINYMCE_EXTRA_MEDIA = {
'js': [
'/path/to/javascript/file/that/defines/CustomFileBrowser',
],
}
```
This would simplify things for [this project](https://github.com/aisayko/Django-tinymce-filebrowser) too.
> Added the "TINYMCE_EXTRA_MEDIA" setting

- tinymce/widgets.py
This parameter appeared in Django 1.11.4 as part of the template-based widget rendering feature and will be a mandatory parameter in Django 2.1
> Add renderer parameter to widgets.TinyMCE.render()

- .travis.yml
- CHANGELOG.rst
- testtinymce/settings.py
- tox.ini
Enable Django 2.2 test environment.
Related to #251 issue.
> Upgrade test matrix to include Django 2.2.

- tinymce/tests/test_widgets.py
- tinymce/widgets.py
The language file name is currently being retrieved/built from the `LANGUAGE_CODE` setting or more specifically from `django.utils.translation.get_language()`, and then being parsed by `widgets.py` line 126 (`language = language[:2] if language is not None else "en"`).
_**This does not work anymore with the new file structure, and generates a bug.** I.e. `fr_FR.js`, `pt_PT.js` cannot be used._
For that reason this pull request is changing the `language` standards of the project to `xx_YY`, where xx is the language and YY is the dialect, to be in sync with naming convention on translation files of TinyMCE5.
> Fix issue with language configuration

- tinymce/templates/tinymce/filebrowser.js
- tinymce/widgets.py
Fixed django-filebrowser compatibility as requested in Issue #303 
There is a similar pull-request in the https://github.com/smacker/django-filebrowser-no-grappelli repo containing the nessesary patches on the side of django-filebrowser
> Added django-filebrowser compatibility to tinymce-v5

- tinymce/views.py
- tinymce/widgets.py
force_text() will be removed in Django 4.0 and is deprecated in favor of force_str()
> Changed force_text() to force_str()

- CHANGELOG.rst
- tinymce/static/django_tinymce/init_tinymce.js
In Django 4.1, the 'formset:added' event is a native JS event.
See https://github.com/django/django/commit/eabc22f91
> Add compatibility with Django 4.1 formset added event

- setup.py
Avoid the installation of the test suite in the top-level directory of Python's site-lib directory.
This should fix issue #355.
> setup.py: Don't install the tests directory

- tests/test_widgets.py
- tinymce/widgets.py
I would like to translate custom style names defined in TINYMCE_DEFAULT_CONFIG, but this code throws TypeError: Object of type __proxy__ is not JSON serializable
```python
'table_class_list': [
{'title': 'None', 'value': ''},
{'title': _('Wide'), 'value': 'u-wide'},
]
```
> This module don't handle translated options (gettext_lazy or pgettext_lazy)

- CHANGELOG.rst
- tinymce/settings.py
This reverts commit db466745ad0082931d1d4ed3d0a0894d4fdc6594. See issue #430.
> Revert "Fixes #420: Switch to staticfiles_storage.url() to reference JS files

- tinymce/static/django_tinymce/init_tinymce.js
Widgets created from inlines may contain the default prefix '__prefix__' in the selector attribute. This change uses the element id instead to initialize TinyMCE.
> fix selector for elements using '__prefix__'

- CHANGELOG.rst
- MANIFEST.in
Regression in 3f90ac9a558398fcba6371f4f6416b1c226439b8
> Fixes #454 - Reintroduce the MANIFEST.in file

- tinymce/settings.py
This PR removes the second occurrence of plugin "code" which is also mentioned on the previous line.
> Remove plugin "code" mentioned twice

- tests/settings.py
- tests/testapp/admin.py
- tinymce/static/django_tinymce/admin_tinymce.css
- tinymce/widgets.py
The standard CSS for the `django.contrib.admin` app contains this:
```
@media (max-width: 1024px) {
textarea {
max-width: 100%;
max-height: 120px;
}
}
```
(see https://github.com/django/django/blob/main/django/contrib/admin/static/admin/css/responsive.css)
This limits the height of the textarea used by TinyMCE's HTML source editor (the "Source Code" button), when using TinyMCE inside the Django admin app, in a 1024-pixel-or-smaller window.  Combined with TinyMCE's styling, the result is unattractive and unintuitive.
(It's likely that the same problem affects any other textareas used by TinyMCE or third-party plugins, but the "Source Code" feature is the only one I know about.)
Of course it's possible for a site to override this using custom stylesheets (though it's not totally obvious how …
> Fix ugly HTML source editor when TinyMCE is used inside Django admin

- tinymce/static/django_tinymce/init_tinymce.js
Add `media_url_resolver` to the list of function, so it will be JS evaluated, if present.
From https://www.tiny.cloud/docs/tinymce/latest/media/#media_url_resolver:
> This option allows you to specify a function that will be used to replace TinyMCE’s default media embed logic with your own, custom logic.
> init_tinymce.js: add `media_url_resolver` function

- docs/usage.rst
**What does this PR do?**
-  Updates TinyMCE documentation to use link_list and image_list instead of deprecated external_link_list_url and  external_image_list_url.
- Provides examples of JSON responses required by the new options.
**Why?**
- The old options no longer work in recent TinyMCE versions.
- **Issue**
- fixes #486
> Update TinyMCE image_list and link_list documentation
